# Generated by Django 5.1.3 on 2024-12-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Вибране', 'verbose_name_plural': 'Вибране'},
        ),
    ]
