# Generated by Django 5.1.3 on 2024-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysclothing',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
