# Generated by Django 5.1.3 on 2024-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('category', models.CharField(choices=[('shirts', 'Сорочки'), ('tshirts', 'Футболки'), ('jeans', 'Джинси'), ('jackets', 'Куртки'), ('suits', 'Костюми'), ('shoes', 'Взуття'), ('accessories', 'Аксесуари')], max_length=100, verbose_name='Категорія')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, verbose_name='Розмір')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ціна зі знижкою')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mens_clothing/', verbose_name='Зображення')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Матеріал')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Чоловічий одяг',
                'verbose_name_plural': 'Чоловічий одяг',
                'ordering': ['-created_at'],
            },
        ),
    ]
